project_id = "oxwizikytcdevwkjaegq"

[functions.scrape-sou-index]
verify_jwt = false

[functions.scrape-regeringen-document]
verify_jwt = false

[functions.process-task-queue]
verify_jwt = false

[functions.scrape-sou-metadata]
verify_jwt = false

[functions.process-sou-pdf]
verify_jwt = false

[functions.test-stage-machine]
verify_jwt = false